export const FETCH_USER_GENERAL_ACTION              = 'FETCH_USER_GENERAL_ACTION';
export const FETCH_USER_TRANSACTIONS_ACTION         = 'FETCH_USER_TRANSACTIONS_ACTION';
export const FETCH_USER_ORDERS_ACTION               = 'FETCH_USER_ORDERS_ACTION';
export const PENDING_FETCH_USER_GENERAL_ACTION      = 'PENDING_FETCH_USER_GENERAL_ACTION';
export const PENDING_FETCH_USER_TRANSACTIONS_ACTION = 'PENDING_FETCH_USER_TRANSACTIONS_ACTION';
export const PENDING_FETCH_USER_ORDERS_ACTION       = 'PENDING_FETCH_USER_ORDERS_ACTION';
