export const FETCH_USER_GENERAL_ACTION         = 'FETCH_USER_GENERAL_ACTION';
export const PENDING_FETCH_USER_GENERAL_ACTION = 'PENDING_FETCH_USER_GENERAL_ACTION';

export const FETCH_USER_TRANSACTIONS_ACTION         = 'FETCH_USER_TRANSACTIONS_ACTION';
export const PENDING_FETCH_USER_TRANSACTIONS_ACTION = 'PENDING_FETCH_USER_TRANSACTIONS_ACTION';

export const FETCH_USER_ORDERS_ACTION         = 'FETCH_USER_ORDERS_ACTION';
export const PENDING_FETCH_USER_ORDERS_ACTION = 'PENDING_FETCH_USER_ORDERS_ACTION';

export const USER_TRANSACTIONS_SUBMIT_ACTION  = 'USER_TRANSACTIONS_SUBMIT_ACTION';
export const USER_TRANSACTIONS_RESET_ACTION   = 'USER_TRANSACTIONS_RESET_ACTION';
export const USER_TRANSACTIONS_PENDING_ACTION = 'USER_TRANSACTIONS_PENDING_ACTION';

export const USER_ORDERS_SUBMIT_ACTION  = 'USER_ORDERS_SUBMIT_ACTION';
export const USER_ORDERS_RESET_ACTION   = 'USER_ORDERS_RESET_ACTION';
export const USER_ORDERS_PENDING_ACTION = 'USER_ORDERS_PENDING_ACTION';
